4teamwork/ftw.publisher.core

test-plone-4.3.4.cfg

We have a problem when comparing text values:
https://github.com/plone/Products.CMFPlone/issues/532
This breaks our tests and our implementation, so we drop the support for now.

Drop Plone 4.3.5 support for now (not testing against it).

---

docs/HISTORY.txt
ftw/publisher/core/adapters/dx_field_data.py
ftw/publisher/core/tests/profiles/dexterity/types/ExampleDxType.xml
ftw/publisher/core/tests/test_dexterity.py
setup.py

This adds support for already published related objects.
It does not support updating backreferences for dexterity objects yet.

Support dexterity relations.

---

docs/HISTORY.txt
ftw/publisher/core/tests/test_utils.py
ftw/publisher/core/utils.py

tuples and sets were converted to lists.
With dexterity it is important that those types are kept and not converted to lists.
@maethu

Keep tuple / set types when sending data.

---

ftw/publisher/core/adapters/dx_field_data.py
ftw/publisher/core/tests/test_utils.py
ftw/publisher/core/utils.py

The problem is that when source and target Plone sites run on the same
Zope instance dexterity relations may be looked up wrong.
When an the relation target is not yet on the target site it is
found from the target site on the source site when queried with the
absolute path.
Therefore we should always use relative paths when putting paths on the wire.

dx references: fix wrong object problem.

---

docs/HISTORY.txt
ftw/publisher/core/adapters/portlet_data.py

Most portlet assignment classes are named "Assignment", that's why the class name was hard coded in the portlet data collector.
But assignment classes may be named differently.
We therefore need to also send the class name and instantiate it correctly.

portlets: support alternate assignment class names

---

ftw/publisher/core/adapters/configure.zcml
ftw/publisher/core/adapters/ftw_simplelayout.py
ftw/publisher/core/tests/test_ftw_simplelayout_adapters.py

The content of simplelayout pages consist of blocks which have usually no workflow and share the publishing cycle with the page.
In order to share the publishing cycle correctly, we need to not publish any delete jobs for (block-) objects which are considered simplelayout content.
For solving this problem, a `is_sl_contentish` function is introduced, which decides which objects are part of the simplelayout content of a simplelayout container.
This checks may be recursive since there are folderish simplelayout blocks, such as the listingblock, which may contain non-simplelayout objects.
When those nested objects do not have a workflow, they share the publishing cycle of the simplelayout container (parent of the parent) and are thus considered simplelayout contentish.
The …

ftw.simplelayout: remove deleted contentish children.

---

docs/HISTORY.txt
ftw/publisher/core/adapters/configure.zcml
ftw/publisher/core/adapters/dx_field_data.py
ftw/publisher/core/adapters/ftw_simplelayout.py
ftw/publisher/core/tests/test_ftw_simplelayout_adapters.py

:construction: based on https://github.com/4teamwork/ftw.publisher.core/pull/26
When publishing dexterity objects where the description was not set, the
description may be str instead of unicode because of a bad default.
https://github.com/plone/plone.dexterity/pull/33
https://github.com/plone/plone.dexterity/pull/35
We change empty str descriptions to empyt unicodes for preventing this error.

Prevent "ValueError: Description must be unicode."

---

docs/HISTORY.txt
ftw/publisher/core/adapters/configure.zcml
ftw/publisher/core/adapters/ftw_servicenavigation.py
ftw/publisher/core/tests/test_ftw_servicenavigation.py
setup.py
sources.cfg

The ftw.servicenavigation data collector sends the data of ftw.servicenavigation stored in the annotation of the Plone site root and of ftw.subsites.

Add data collector for ftw.servicenavigation data.

---

docs/HISTORY.txt
ftw/publisher/core/adapters/dx_field_data.py

There are sometimes situations where dxterity relations has no
to-path. In this case the relation is broken and we cannot publish it,
so we just remove it.
/cc @maethu

Fix error when publishing DX relation with no target.

---

docs/HISTORY.txt
ftw/publisher/core/adapters/configure.zcml
ftw/publisher/core/adapters/plone_app_event.py

plone.app.event has a special handling for timezones: it uses fake time zones which are replaced when the modified event is triggered. The publisher does not trigger the modified event, so we need to call the cleanup function manually.

Fix plone.app.event timezone problems.

---

docs/HISTORY.txt
ftw/publisher/core/adapters/backreferences.py

When there are broken back references we should ignore them. This makes back references extraction more robust.
Fixes https://github.com/4teamwork/ftw.publisher.sender/issues/39

Backreferences: awoid error with broken references

---

ftw/publisher/core/adapters/dx_field_data.py
ftw/publisher/core/tests/test_dexterity.py

When an object is published for the second time, having the same relation, it should not be readded to the relation catalog but updated instead.
By using ``updateRelations`` instead of ``addRelations`` this is handled correctly by ``z3c.relationfield``.

Awoid duplicate relations in catalog when republishing.

---

docs/HISTORY.txt
ftw/publisher/core/adapters/properties_data.py
ftw/publisher/core/tests/test_properties_adapter.py

Publishing the layout property on plone site root has been introduced in 2.7.3 but used to fail if the plone site root on the receiving end does not have the layout property.
We must therefor check if the property is available before trying to delete it in order to prevent the following error raised in `manage_delProperties()`: BadRequest: The property <em>layout</em> does not exist.

Improve publishing the layout property on plone site root.

---

docs/HISTORY.txt
setup.py

The "splinter" extra has been removed from "ftw.testing". Use "ftw.testbrowser" instead!
See https://ci.4teamwork.ch/builds/92634/tasks/135499

Fix tests by no longer installing the "splinter" extra.

---

docs/HISTORY.txt
ftw/publisher/core/testing.py
ftw/publisher/core/tests/behaviors.py
ftw/publisher/core/tests/behaviors.zcml
ftw/publisher/core/tests/builders.py
ftw/publisher/core/tests/test_datagrid_with_relations.py
ftw/publisher/core/utils.py
setup.py

This implicitly supports RelationValues for datagrid fields, since they store list of dicts.

Implement relations values for nested structures

---

docs/HISTORY.txt
ftw/publisher/core/tests/test_utils.py
ftw/publisher/core/utils.py

Add method `make_path_absolute` to provide a util to make a path absolute again by joining it onto the site root path.
This method is the counterpart to `make_path_relative`.

Add conterpart method to make_path_relative to make relative path absolute again

---

setup.py

Fix tests by pinning down `collective.z3cform.datagridfield` to a Plone 4 compatible version for the `tests_plone4` extra.
(Plone 4 support got [dropped in `1.4.0`](https://github.com/collective/collective.z3cform.datagridfield/blob/master/CHANGES.rst#140-2019-02-21), which now contains a hard dependency on Plone 5.)
Fixes this failure: https://ci.4teamwork.ch/builds/228428/tasks/375188
A similar fix would solve this issue for `ftw.publisher.sender` (it would probably make sense to require `ftw.publisher.core[tests_plone4]` in the `ftw.publisher.sender[tests_plone4]` extra, no?) - but there's still other test failures cropping up in `.sender` (failing assertions, simplelayout related).

Pin down c.z.datagridfield for Plone 4 tests:

---

development.cfg
docs/HISTORY.txt
ftw/publisher/core/adapters/simplelayout_utils.py
ftw/publisher/core/tests/test_ftw_simplelayout_adapters.py
setup.py

`is_sl_contentish` now also returns `false` if the content is trashed by ftw.trash.

ftw.trash support für ftw.simplelayout content

---

docs/HISTORY.txt
ftw/publisher/core/adapters/dx_field_data.py

The default plone types implement the IShortName behaviour which when
applying on the receiver side wants to rename the existing object to the
same name it already has. But because it already has that name it
appends a -1 and the rest of the publishing fails.

Fix publishing of types with IShortName behaviour

---

development.cfg
docs/HISTORY.txt
ftw/publisher/core/adapters/children.py
setup.py
test-plone-4.3.x-trash.cfg
test-plone-5.1.x-trash.cfg

```python
Traceback (most recent call last):
File "/home/zope/eggs/ftw.publisher.receiver-2.2.1-py2.7.egg/ftw/publisher/receiver/browser/views.py", line 39, in __call__
state = self.handleRequest()
File "/home/zope/eggs/ftw.publisher.receiver-2.2.1-py2.7.egg/ftw/publisher/receiver/browser/views.py", line 90, in handleRequest
return self.pushAction(metadata, self.data)
File "/home/zope/eggs/ftw.publisher.receiver-2.2.1-py2.7.egg/ftw/publisher/receiver/browser/views.py", line 275, in pushAction
adapter.setData(data[name], metadata)
File "/home/zope/eggs/ftw.publisher.core-2.12.0-py2.7.egg/ftw/publisher/core/adapters/children.py", line 34, in setData
self.context.working_copy.manage_delObjects(ids_to_delete)
AttributeError: working_copy
```
The problem occurs when publishing a page and the …

Fix bug when deleting children without ftw.trash installed

---

docs/HISTORY.txt
ftw/publisher/core/adapters/configure.zcml

In Plone 4, plone.app.event used to separate the timezone info from the dates, which made it necessary to have a custom publisher adapter for fixing the start and end values.
In Plone 5, plone.app.event has a different implementation which breaks when the fix is used because the fix uses Zope DateTime which is no longer wise.
The problem was that the receiver side has stored `GMT+1` as timezone, which is not a valid `pytz` timezone, causing errors such as:
```
UnknownTimeZoneError: (UnknownTimeZoneError('GMT+1',), <function _p at 0x7fa70a7d4f50>, ('GMT+1',))
```

Disable plone.app.event fix for Plone 5.

---

docs/HISTORY.txt
setup.py
test-plone-4.3.x-trash.cfg
test-plone-4.3.x.cfg

plonetheme.onegov 4.x drops Plone 4.3 compatibility so we need an
earlier version.

Fix plone4 test setup

---

docs/HISTORY.txt
ftw/publisher/core/belongs_to_parent.py
ftw/publisher/core/tests/test_belongs_to_parent.py

This function is used in ftw.publisher.sender https://github.com/4teamwork/ftw.publisher.sender/pull/73 but belongs to the belongs_to_parent like functions, thus we add and test it in here.
❗️ Based on https://github.com/4teamwork/ftw.publisher.core/pull/64 to fix tests. Update base branch before merging.

Add function to get parent belonging to child

---

docs/HISTORY.txt
ftw/publisher/core/adapters/portlet_data.py
ftw/publisher/core/tests/test_portlet_adapter.py

Since it set the attr as regular list right now, it leads to strange behavior if you have a multi-instance setup

"_order" Attribute on portlet manager needs to be a persistent list

---

docs/HISTORY.txt
ftw/publisher/core/adapters/configure.zcml
ftw/publisher/core/adapters/constrain_types.py
ftw/publisher/core/tests/test_constrain_types_adapter.py

It's possible to restrict addable types. In plone 5, these settings weren't published. With the new adapter the settings are published.
Part of https://github.com/4teamwork/ogb/issues/180

Add constrain types adapter.

---

docs/HISTORY.txt
ftw/publisher/core/adapters/dx_field_data.py
ftw/publisher/core/tests/interfaces.py
ftw/publisher/core/tests/profiles/dexterity/types.xml
ftw/publisher/core/tests/profiles/dexterity/types/DXDateAndTime.xml
ftw/publisher/core/tests/test_dexterity.py

Two problems existed:
- The datetime was not always transferred as ISO-8601 formatted string
- The timezone was converted to GTM on the receiving side. The `pytz`
module does not understand GMT timezones except for GMT+0 (which is why
it worked until now)
Possible solutions:
- Correct the timezone to something understandable by `pytz` on the
receiver side.
- Send the timezone separately as something that `pytz` already
understands.
We choose solution two because it is easier to implement. For solution 1
we would have had to create our own `GMT` parser that makes it `pytz`
compatible or get another package to do it.
With the second solution, we just strip the timezone and send separately
to get a string on the receiver side which `pytz` already understands.
This, however, means we need to …

Fix timezone transfer from sender to receiver

---

docs/HISTORY.txt
ftw/publisher/core/adapters/configure.zcml
ftw/publisher/core/adapters/ftw_logo.py

This forces the creation of a new cachkey, which forces the browser to show a new logo, even if it's caches by a proxy.

ftw.logo integration - create new cachkey upon receiving a logo.

---

docs/HISTORY.txt
ftw/publisher/core/tests/behaviors.py
test-plone-5.1.x-trash.cfg
test-plone-5.1.x.cfg

See
https://github.com/collective/collective.z3cform.datagridfield/commit/3d4064a47a9062394acab8f2b65e61025875a150#diff-b7466768d5acffdf1a9b06abfb886a06ff495ef020cc04fea1b3d42b622c1c48
Thus the shorter module import did no longer work.

Fix collective.z3cform.datagridfield import.
